name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.AIzaSyA-28qx7ESIwCka76Pu0O3wDkf1nRSgpFI }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.taskgrid-gx2rk.firebaseapp.com }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.taskgrid-gx2rk }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.taskgrid-gx2rk.firebasestorage.app }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.1020397139722 }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.1:1020397139722:web:bf65cf8c82d1dbc5ae2cf3 }}
     

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and Export Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
